### ISSUE TITLE
Error in file public data

### ISSUE THREAD

**Issue by ypriverol** [compomics/ThermoRawFileParser#108]
This file has an error: 

```
2021-03-07 23:42:01 INFO Started parsing MFA389.raw
2021-03-07 23:42:01 ERROR Error opening (ThermoFisher.CommonCore.RawFileReader.Facade.RawFileLoader) - MFA389.raw
```
http://ftp.pride.ebi.ac.uk/pride/data/archive/2020/05/PXD014145/MFA389.raw

**Comment by caetera** [comment]
Hi @ypriverol,

The file was converted to mzML without any errors with the latest release version of TRFP (1.3.2) on Windows and Linux (Ubuntu 18.04.5, Mono 6.12). Could you provide more details how to reproduce the error?

**Comment by ypriverol** [comment]
It actually works. Apparently, mono 6 if you use symbolic links, it will not work. if the file you are trying to convert is a symbolic link to another file, it will not work on mono 6.

**Comment by bernt-matthias** [comment]
Is there a way to fix this? The Galaxy wrapper (actually any conda installation) suffers from the same problem since mono 6 is available. Still using a symlink seems very reasonable and handy. 

I see the following ways to solve this (roughly ordered by my preference): 

- an actual fix
- enforcing mono <6 in the bioconda recipe
- enforcing mono <6 in the Galaxy wrapper
- using a copy instead of a symlink

**Comment by caetera** [comment]
Hi @bernt-matthias 

the actual fix should likely be issued by mono developers. I am not sure how to approach it from the TRFP side, despite to check if we are on mono 6 and the input file is a symlink and try to fail with some sensible error or attempt to recover (copy file, "expand" the symlink). It sounds like quite an ugly fix to me.

**Comment by bernt-matthias** [comment]
Thanks for you efforts.

Then I would go for option 2 for now. 

Could you open an issue at the mono repository? I

**Comment by bernt-matthias** [comment]
https://github.com/bernt-matthias/bioconda-recipes/pull/new/topic/trfp-mono

**Comment by caetera** [comment]
I will need to do a little bit of investigation to localize the problem a bit better before I can open the issue.

**Comment by caetera** [comment]
A small update. I am afraid it is not mono, since I could reproduce the same error on native Windows, i.e. if the file is a symlink the library from Thermo refuses to open it. Surprisingly, there is no obvious and platform independent way to get the target of a symlink from C#. I will keep looking into it.

**Comment by bernt-matthias** [comment]
Thanks for the update. Then its odd that it works for mono<5, or?

**Comment by caetera** [comment]
It is, I don't have any explanation for it

**Comment by caetera** [comment]
I have implemented a fix for that (#146); still lacking testing on Mac platform. Any help will be appreciated.

**Comment by bernt-matthias** [comment]
Unfortunately I don't have a Mac .. in the worst case one could abuse the bioconda CI pipelines (install from the github repo and add a test).

**Comment by caetera** [comment]
I found a volunteer - it seems to work on Mac as well (with an extra "lower-the-security", only for symlinks). I plan to make a release in the next few days, suggest disabling `mono < 6` in bioconda recipe and hope for the best.
