### ISSUE TITLE
Wrong Orbitrap Exploris 480 CV? 

### ISSUE THREAD

**Issue by rolivella** [compomics/ThermoRawFileParser#120]
Hello

I'm converting Orbitrap Exploris 480 data and I get this "Invalid_SN_0001" for the "instrument serial number": 

```xml
  <referenceableParamGroupList count="1">
    <referenceableParamGroup id="commonInstrumentParams">
      <cvParam cvRef="MS" accession="MS:1000483" value="" name="Thermo Fisher Scientific instrument model" />
      <cvParam cvRef="MS" accession="MS:1000529" value="Invalid_SN_0001" name="instrument serial number" />
    </referenceableParamGroup>
  </referenceableParamGroupList>
```

According the CV this code should be "MS:1000494" instead. 

Could you check it? 

Thank you!

**Comment by rolivella** [comment]
Method error from their side.

**Comment by rolivella** [comment]
Oops, I closed this issue by mistake. I reopen it.

**Comment by caetera** [comment]
Hi @rolivella,

Thank you for reporting this. Complete Exploris family should be supported, i.e. it should resolve into `MS:1003028` for Exploris 480, I can confirm that it does not and that will be fixed.
I cannot, however, confirm the problem with oddly looking serial number. Exploris files I have tested all have valid serial number. I have seen, however, that sometimes the serial number field in the raw file contains something completely different most likely due to wrong configuration of the acquisition PC. Do you have access to any vendor RAW file viewer such as FreeStyle or QualBrowser or can you share the raw file for the inspection?

**Comment by rolivella** [comment]
Hi @caetera. We checked and there're some Exploris that were bought before the commercial release and still experimental and we think that for that reason there's this "Invalid_SN_0001". I don't think that we have to worry about that so I close the issue. Thank you.
