### ISSUE TITLE
missing peaks after conversion

### ISSUE THREAD

**Issue by Seb-Leb** [compomics/ThermoRawFileParser#127]
Hello,

I used ThermoRawFileParser to convert a raw file to mgf and came across this issue while comparing that to the output of the msms.txt file resulting from a maxquant search of the raw file. This may be normal and known behaviour but I am not sure what to make of it. Some peaks annotated by maxquant are simply absent in the mgf conversion (centroided). With peak picking disabled, I can see entries in the right m/z range but the intensities are 0.0 (they are >0 in the maxquant output). 
Could this be something that maxquant does that I am not aware of? or are there peak intensities in the raw file that don't make it to the mgf?
I'm attaching a link to a zip containing the raw, mgf and maxquant outputs: [here](https://drive.google.com/file/d/1SfWFBbxuKhHyVWm07G6GVRNun-pWgWJC/view?usp=sharing)
For example scan number 36942 shows peaks at (1218.64370096771, 100000) and (1459.75527233851, 300000)
but in the converted mgf we only see this at the end of the spectrum:
```
...
949.7034794 0.0000000000
1020.3642499 0.0000000000
1020.3951612 0.0000000000
1020.4260738 0.0000000000
1020.4569879 0.0000000000
1020.4879034 2094.7021484375
1020.5188202 4424.8017578125
1020.5497385 5908.2734375000
1020.5806582 5498.1396484375
1020.6115793 3511.4694824219
1020.6425017 0.0000000000
1020.6734256 0.0000000000
1020.7043509 0.0000000000
1020.7352776 0.0000000000
1601.0371915 0.0000000000
1601.0979476 0.0000000000
1601.1587071 0.0000000000
1601.2194701 0.0000000000
END IONS
```

Thanks!

**Comment by caetera** [comment]
Hi @Seb-Leb,

thank you for using ThermoRawFileParser. I have few considerations regarding your issue.
First, in TRFP we exclude so-called "reference and exception data" during the conversion by default, you can disable this feature using the `-x, --includeExceptionData` option in command line. Typically, there are only few peaks in the spectrum that are marked as reference (for example lockmass) or exception (for example, split peaks) by the mass spectrometer. MaxQuant developers might choose to include all the data during their processing.
Second, the results reported in msms.txt file might be filtered or processed in some way. Personally, I have observed that output of MaxQuant does not always make sense. Since MaxQuant source is not readily available it is hard to deduce how the reports are generated. 

In the case of spectrum 36942 there is no peak at 1218 or 1459. I used vendor software as a reference for that purpose. Vendor software even with exception peaks enabled produces the same output as TRFP. Thus, I believe it is worth asking MaxQuant people what is happening here.

**Comment by Seb-Leb** [comment]
Thank you for the quick response! I figured it might be something to do with MaxQuant.. I don't have easy access to proprietary software to check the raw spectra (I didn't run maxquant myself..) so I could check whether those peaks were there. But I guess that clarifies where the problem is from..
Thanks again!
