### ISSUE TITLE
Parsing mzML with xmllint

### ISSUE THREAD

**Issue by rolivella** [compomics/ThermoRawFileParser#131]
Hi, 

I'm trying to parse data from the mzML files using the `xmllint` tool. It works fine when the mzML is not indexed but for the indexed ones it fails. For instance, if I want to extract the TIC of each scan: 

`xmllint --xpath '/mzML/run/spectrumList/spectrum/cvParam[contains(@accession,"MS:1000285")]/@value' 190215_Q_QC01_01_32.indexed.mzML`

I get: 

`XPath set is empty`

While the same file not indexed returns the output without any problem. 

Any idea? Thanks!

**Comment by rolivella** [comment]
Hi @caetera 

I found the issue. At the end what does not like to `xmllint` is this: 

`<indexedmzML xmlns="http://psi.hupo.org/ms/mzml"`

I think that as "http://psi.hupo.org/ms/mzml" does not exist, the parser stops to work properly. 

Do you know when this URL is inserted into the output mzML? If it's the TRFP that do it, I don't see the point because is not working...

Thanks!

**Comment by caetera** [comment]
@rolivella this namespace is a part of mzML specification; pretty much all parsers use it.
I have found however, that indexed mzML produced by TRFP still reference non-indexed xml schema location, maybe this is the reason for the error.
I will issue the fix anyway, but if you want to quickly check it, just replace  the first element with 
`<indexedmzML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd" xmlns="http://psi.hupo.org/ms/mzml">`

**Comment by rolivella** [comment]
@caetera great, thanks!

**Comment by caetera** [comment]
Do you mean that it works after the manual change?

**Comment by rolivella** [comment]
Yes, it works after manually removing `xmlns="http://psi.hupo.org/ms/mzml` from mzML file.

**Comment by caetera** [comment]
I think I figured it out. The problem is namespace used in mzML, and that is something that cannot be changed in the output.

According to https://stackoverflow.com/questions/43694722/extract-value-from-xml-file-with-namespaces-by-using-xmllint-in-bash you can use `*[local-name()='']` to work around it.
Using the following command I could parse out all TIC values.
`xmllint --xpath '//*[local-name()="spectrum"]/*[local-name()="cvParam"][contains(@accession,"MS:1000285")]/@value' somefile.mzML`

**Comment by rolivella** [comment]
Great, many thanks, it works fine!
