### ISSUE TITLE
Error opening (ThermoFisher.CommonCore.RawFileReader.Facade.RawFileLoader)

### ISSUE THREAD

**Issue by wholtz** [compomics/ThermoRawFileParser#143]
I have several files that fail to convert:
```bash
$ ls -l error.raw 
-rw-r--r--  1 me  staff  71303364 Jul 13 13:48 error.raw
$ docker run -it --rm -v $(pwd):/mnt quay.io/biocontainers/thermorawfileparser:1.3.4--ha8f3691_0 ThermoRawFileParser.sh -i=/mnt/error.raw -o=/mnt --logging=1
2022-07-13 20:59:59 INFO Started parsing /mnt/error.raw
2022-07-13 21:00:00 ERROR Error opening (ThermoFisher.CommonCore.RawFileReader.Facade.RawFileLoader) - /mnt/error.raw
$ 
```

Any recommendations on how I can get more information about what the underlying problem is? 

I tried changing the log level by replacing `INFO` with `ALL` in `/usr/local/bin/log4net.config`, but it did not increase the verbosity.

**Comment by caetera** [comment]
Hi @wholtz,
to increase the verbosity provide additional argument `-l 1` (logging), it won't however help you much in that case, since the error you face seem to come from the libraries provided by Thermo (they do not give much debug information to the outside world). It indicates that the the RAW file is in the error state. Maybe the file itself is corrupted? Can you open/work with it using some other software? Once I can solve that sort of problems for a file from PRIDE by downloading it once again (I guess, it was broken in transfer/writing to the disk).
