### ISSUE TITLE
mzML intensity unit confusion

### ISSUE THREAD

**Issue by martinPasen** [compomics/ThermoRawFileParser#156]
Hello,
in this standard https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo it says that ms1 intensities can have multiple units:
number of detector counts
percent of base peak
counts per second
percent of base peak times 100
absorbance unit

when i convert raw (generated on fusion or QE) to mzML the ms1 intensities have a unit 'number of detector counts' which is defined as "The number of counted events observed in one or a group of elements of a detector.". From the name and the definition I understand it says how many ions were collected and observed during the collecting period. If we wanted to normalise it to one second and get 'counts per second' we need to divide this number by the 'ion injection time'.

At least that is how i understand it. But i have a suspicion that even though the unit is 'number of detector counts' it is already normalised to one second. This suspicion comes from comparison of area under the chromatogram that i have computed and that Skyline computes. Also in the above mentioned standard this is written:

name: intensity unit
def: "Intensity units are commonly arbitrary. Detected in counts per second (cps) when using counting detectors, but measured in volts when using analog detectors." [PSI:MS]

Could you please shed a light on this?

thank you for the nice codebase and have a nice day :)
Martin

**Comment by caetera** [comment]
Hi @martinPasen,

if one wants to be precise, the story is a bit more convoluted - Orbitrap uses image current to "count" ions in the detector, next, raw image current (frequency signal) is Fourier-transformed to the m/z-intensity signal, and, also, some further transformation (calibration function, baseline subtraction, etc) is applied before it is stored as spectra in the file. Thus, the values stored in the spectra are "artificial", i.e. a peak with an intensity of one million does not correspond to one million ions "counted" by the detector. The vendor itself calls it "normalized ion current" (they are, indeed, normalized to ion accumulation time) and the value is promised to be proportional to ion flux, but it is (precisely speaking) neither "counts per second", nor "number of detector counts". I guess, it is some sort of tradition to use "number of detector counts" for mass spectra, as it was in the early days of mass spectrometry when counting detectors were employed.
Is there any specific reason why you want to have ion counts?

**Comment by martinPasen** [comment]
Sorry for not being specific. I am not interested in ion counts. I am interested in the fact whether the MS1 intensities are normalised to 1 second or not. 

If I understand it correctly, the spectrometer is collecting the ions for some time and then pushes them all at once into orbitrap, measures them and outputs some reading that as you mentioned above is later processed (i have data from Fusion/ orbitrapQE). From that we get MS1 spectrum. Position of the peaks defines m/z and the amplitude of the peak is proportional to the count of ions that were measured (more ions -> higher peak). The peak intensities are used for quantification. 

My question is whether the peak intensities are already normalised to one second (divided by the time we were collecting the ions) or not. So if we would have a steady flow of ions, would we get the same peak intensities if we collected for 1 second compared to 2 seconds? Or in the 2 second scenario would we get peaks with doubled height?

**Comment by caetera** [comment]
The short answer is yes, they are normalized by accumulation time.

In fact, the instrument always collects (or at least tries to collect) not more than a certain number of charges (i.e. a 3+ ion will be counted not as 1 [ion], but as 3 [charges])  - the **AGC Target**. These are sent to the Orbitrap analyzer to acquire a spectrum. More precisely, the instrument uses a so-called, prescan - a rapid scan with a fixed small injection time - to assess current ion flux, next, it calculates the time necessary to accumulate the requested amount of charges. Since the estimation of ion flux is not always precise and, moreover, the ion flux can change between the prescan and actual scan, there is another detector that measures the _real_ number of ions pushed to the Orbitrap. This _real_ number is then used, among other things, to employ the correct calibration function (and it is also stored in the raw file in, the so-called, scan trailer). 

You might find the following papers useful:

* Belov, M. E.; Zhang, R.; Strittmatter, E. F.; Prior, D. C.; Tang, K.; Smith, R. D. Automated Gain Control and Internal Calibration with External Ion Accumulation Capillary Liquid Chromatography-Electrospray Ionization-Fourier Transform Ion Cyclotron Resonance. Anal. Chem. 2003, 75(16), 4195−4205.

* Belov, M. E.; Rakov, V. S.; Nikolaev, E. N.; Goshe, M. B.; Anderson, G. A.; Smith, R. D. Initial Implementation of External Accumulation Liquid Chromatography/Electrospray Ionization Fourier Transform Ion Cyclotron Resonance with Automated Gain Control. Rapid Commun. Mass Spectrom. 2003, 17(7), 627−636.
```

**Comment by martinPasen** [comment]
Thank you very much :) that was exactly what I was looking for.

Martin
