### ISSUE TITLE
Extracting from specific scan filters

### ISSUE THREAD

**Issue by micro128** [compomics/ThermoRawFileParser#158]
Hello:

I want to use the `xic` subcommand to get chromatograms from MS2. How can I extract chromatograms from specific scan filters?

Example Scan Filter:
ITMS + c NSI Full ms2 575.0000@cid30.00 [159.0000-1500.0000]

Thanks!

**Comment by caetera** [comment]
Hi @micro128,

yes, it is possible. You just need to add `scan_filter` property to the input JSON file. You can use any valid scan filter format. Please note, however, that only a basic validation is performed by TRFP, i.e., ensure the filter string is valid, otherwise you will end up with an empty XIC.

Please, see example below:
```
   {
      "mz":1352.3442055110409,
      "rt_start":14.0600881872,
      "rt_end":14.4167198290667,
      "tolerance":5,
      "tolerance_unit":"ppm",
      "comment":"MS2 only",
      "scan_filter":"ms2"
   },
   {
      "mz":1014.5099732499732,
      "rt_start":14.0600881872,
      "rt_end":14.4167198290667,
      "tolerance":5,
      "tolerance_unit":"ppm",
      "comment":"Only ion trap scans"
      "scan_filter":"ITMS"
   },
   {
      "mz":811.8094338933325,
      "rt_start":14.0600881872,
      "rt_end":14.4167198290667,
      "tolerance":5,
      "tolerance_unit":"ppm",
      "comment":"Complete scan filter"
      "scan_filter":"ITMS + c NSI Full ms2 575.0000@cid30.00 [159.0000-1500.0000]" 
   }
]

```

I will likely need to describe it better in the documentation.

**Comment by caetera** [comment]
Closed for now, the readme was updates
