### ISSUE TITLE
Could we add centroid mode (MS1 level peak picking) to Thermo tool?

### ISSUE THREAD

**Issue by subinamehta** [compomics/ThermoRawFileParser#25]
Hello, I am trying to convert raw files to mzml/mgf, but realized that this tool only works for profile mode, Is it possible to add centroid mode (helps with quantitation @MS1 level)?

**Comment by nielshulstaert** [comment]
Hi,

If centroided data is available for a given scan, it is reported by the parser. Sometimes a scan is recorded in profile mode but also has centroided data, in that case the centroided data is reported. 

I'll release a new version soon that also reports the precursor intensity when the MS1 centroided data is available (see an mzML entry example below).

`
<cvParam cvRef="MS" accession="MS:1000042" value="725709.25" name="peak intensity" unitAccession="MS:1000131" unitName="number of detector counts" unitCvRef="MS" />             
`
I've added the -p, --profiledata flag for MGF output because the MGF output file can get really big if the MS2 spectra are recorded in profile mode.

Best regards,

Niels Hulstaert

**Comment by subinamehta** [comment]
Hello Niels,

I think the raw files will have the MS1 data, I have used MSconvert (vendor support) and for that we have to specifically choose peak picking MS1. Hopefully the new version will report the precursor intensity.

Thanks!

Subina

**Comment by subinamehta** [comment]
Hello Niels,

There is another issue that I see with the Thermo tool, it creates a weird Title for the raw files. 
Title comparison:
**With msconvert (vender support)=**

BEGIN IONS
--
TITLE=jrudney_chenx096_20150307_14688_734NS_1D.2.2.2
RTINSECONDS=0.8171
PEPMASS=434.224365234375 270869.09375
CHARGE=2+

**Thermo:**

BEGIN IONS
--
TITLE=mzspec=input.raw: controllerType=0 controllerNumber=1 scan=2
SCAN=2
RTINSECONDS=0.8171
PEPMASS=434.2243652
CHARGE=2+

**Comment by ypriverol** [comment]
@subinamehta This is not actually a "weird" TITLE is a valid mzML wait of a given title to each Spectrum. Suggestions are more than welcome. In this case, also the TITLE can be used as an identifier if you check the msconvert is using the same file name for every TITLE.

**Comment by subinamehta** [comment]
I am just worried that when I run SearchGUI Peptide Shaker on thermo's ".mgf" file and then the Spectrum File name is not going to be similar to the ".raw" file, which might be an issue with our quantitation tools.

**Comment by nielshulstaert** [comment]
@ypriverol should we get rid of the mzspec format title as is it not really intended to be used like this and have the classic TITLE=controllerType=0 controllerNumber=1 scan=339?

**Comment by ypriverol** [comment]
Yes. Do you want me to do the changes?

**Comment by nielshulstaert** [comment]
I've finished the indexed mzML, together with writing the mzML as a stream (instead of keeping the model in memory). I'll include in that version and we can release it next week.

**Comment by ypriverol** [comment]
Cool, if you want you can do a PR and I will review it

**Comment by ypriverol** [comment]
@this issue has been solved.
