### ISSUE TITLE
MS2 precursor ion mass comparison with msconvert

### ISSUE THREAD

**Issue by RonBeavis** [compomics/ThermoRawFileParser#38]
I have been analyzing data from RAW file converted using TRFP and msconvert. The results are similar, except that the TRFP results show that the parent ion mass for a spectrum is more likely to be the A1 peak than I would expect. For the same RAW file, the ratio of A0:A1 identified is 

TRFP A0:A1 = 6697:2000
msconvert A0:A1 =  8650:328

The specific RAW file in this example is

20180827V_JDF_CHDI_Q140_S_2M_HDAC4_R1_E1.raw, from PXD011845, 

but I have found the same sort of effect in the other files I have tested.

**Comment by ypriverol** [comment]
Hi @RonBeavis 

What is the notation A0:A1 ? What is A0 and A1?

**Comment by RonBeavis** [comment]
It is the standard notation for identifying the 13C isotope peaks associated with the MS of organic molecules. The A0 peak is all 12C, A1 has one 13C, A2 had two 13C, etc.

**Comment by RonBeavis** [comment]
Do you need further clarification of what I meant in the original post?

**Comment by nielshulstaert** [comment]
Hi @RonBeavis thanks for taking your time to test our parser. I report the precursor mass provided by the native thermo library. In mzML we also report the _[Thermo Trailer Extra]Monoisotopic M/Z:_ as a user param. Is it better to report the monoisotopic mass as precursor mass when available?

**Comment by mobiusklein** [comment]
It's worth noting that msconvert includes additional heuristic checks to account for historical problems with Thermo's firmware: https://github.com/ProteoWizard/pwiz/blob/master/pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp#L478-L632. This information is *usually* consistent with the value in the scan trailer, though not always. The m/z reported here may reside outside the isolation window, for example. 

Pardon the log scale Y-axis:
![image](https://user-images.githubusercontent.com/1426041/57386853-4394f200-7183-11e9-9663-3d34b08334d1.png)
vs.
![image](https://user-images.githubusercontent.com/1426041/57386949-73dc9080-7183-11e9-8b6c-ee57eb68b0b1.png)

The reason why msconvert *does* deviate from the trailer value is because of the check here: https://github.com/ProteoWizard/pwiz/blob/master/pwiz/data/vendor_readers/Thermo/SpectrumList_Thermo.cpp#L564-L574

Note that these trends will vary by instrument model. You'll get a different distribution of precursor peak errors on a QE series vs. a Lumos for instance.

**Comment by nielshulstaert** [comment]
Ok I'll do some testing and comparisons and get back to you. This is very useful feedback, thanks!

**Comment by nielshulstaert** [comment]
We released a new version (1.1.4) yesterday that should handle this problem. Am I correct to say that this only affects the MGF format and not mzML? The monoisotopic mass reported in the trailer data usually has a 4 digit precision while msconvert reports a similar value but with more digits, I'm not sure what I'm missing. Thanks again for taking your time to test the library and the valuable feedback!

**Comment by mobiusklein** [comment]
I think @RonBeavis's point applies to both mzML and MGF. Even though you report the precursor m/z in the `[Thermo Trailer Extra]Monoisotopic M/Z:` param that ProteoWizard would report in `selectedIon`, tools would have to be "Thermo Trailer"-aware in order to get the same m/z from both  `msconvert` and `TRFP`.

Also, I may be missing some information, but https://github.com/compomics/ThermoRawFileParser/blob/master/Writer/MgfSpectrumWriter.cs#L83-L88 still reads directly from the `IReaction` object, not the trailer value.

-------------
Incidentally, you're reporting a `[Thermo Trailer Extra]Monoisotopic M/Z:` value of -1 for MS1 spectra. I don't think this will break anything, but its extra work and extra space?

**Comment by nielshulstaert** [comment]
Hi @mobiusklein you're right, I removed the `[Thermo Trailer Extra]Monoisotopic M/Z:` for MS1 spectra and the 'selected ion m\z' value in mzML output is now the same as the `PEPMASS` value in the MGF output.

**Comment by mobiusklein** [comment]
I think you settled any comments I had made. I just joined this conversation uninvited though, so I don't know if @RonBeavis  has more to say.
