### ISSUE TITLE
feature request:ThermoRawFileParser to extract batches of spectra/chromatograms

### ISSUE THREAD

**Issue by timosachsenberg** [compomics/ThermoRawFileParser#53]
For spectra or chromatogram visualization (e.g., on a webserver), it might be really useful to allow extraction of a batch of spectra or chromatograms (e.g., as JSON).
Are there any plans and would this be feasible?
Best,
Timo

**Comment by caetera** [comment]
Hi Timo, 
what kind of chromatograms do you have in mind? XICs or just TIC/BasePeak? I made once a small tool that builds a bunch of XICs out of a raw file (it is c# and used MSFileReader inside, thus, moving it to ThermoRawFileReader assemblies should be pretty straightforward) . The output is plaintext, but making it JSON should not be a huge deal as well. I can find some time to work on it further. Later this can be integrated into ThermoRawFileParser if the developers find it appropriate.

**Comment by ypriverol** [comment]
Hi @caetera and @timosachsenberg: 

I'm also interested in that topic. PRIDE is looking for json representation of proteomics data. I suggest that before we implemented this here. We discuss a proposal about how a json representation of an mzML should look like.

**Comment by caetera** [comment]
Hi, @ypriverol,
yes, sure, it would be good to agree with the representation from the start.

**Comment by caetera** [comment]
Hello @timosachsenberg  @ypriverol ,

do you feel this topic (JSON representation, batch LC extraction) can be used as one of the hackathon at EuBIC developer meeting?

For those who are not familiar, here is the link for DevMeeting: https://www.proteomics-academy.org/eubic-dev-meeting-2020

**Comment by ypriverol** [comment]
Yes, sure. e should try to align this with the current efforts to standardize metadata in public repositories.

**Comment by nielshulstaert** [comment]
I have some code that takes a retention time range, m/z and mass tolerance and returns a chromatogram in json format from a colleague I can share. As there are already a lot of command line arguments in the parser, should we try to incorporate this into the parser are create a new project?

**Comment by caetera** [comment]
@nielshulstaert I agree that adding more command-line arguments will be quite "exhausting" already, especially since XICs are quite special case. Maybe it can be included in the current project but as a separate executable? Similar to how it is done in proteowizard: i.e. there is msconvert that is used for conversion of RAW files, and mspicture for extracting 2D maps. Both tools will use partially the same code "behind the scene". Do you think it is a good idea?
On a separate note, including the standardized JSON representation of a complete raw file (I guess it is what @ypriverol suggests), can nicely fit into ThermoRawFileParser, just by adding a new output format (-f=4).

**Comment by caetera** [comment]
On yet even more separate note, the deadline for project submission for the hackathon is just around the corner. IMO both ideas, i.e. developing community-supported JSON-based format for raw files, or expanding ThermoRawFileReader with XIC functionality (either as a standalone tool or as part of its "ecosystem") sound fine. I can do the submission etc, however, I don't want to submit both of them, just because I won't be able to participate in two hackathons in parallel. Thus, it would be nice if you can share your opinion and, of course, I am happy to have more people on board. :)

**Comment by nielshulstaert** [comment]
@caetera yes current project different executable sound good. I'm thinking of going to the hackathon, it would be interesting to contribute to either!

**Comment by caetera** [comment]
@nielshulstaert I have drafted the project proposal for the hackathon. Do you want to be included as a co-author as well? Please, see the draft in G-docs https://docs.google.com/document/d/1llfBcbw1T6aeRblmKl3S4cNoshUpOynOu1gG0tdTVpc/edit?usp=sharing

**Comment by ypriverol** [comment]
@caetera please include my name in the project becuase I’m interested and I will probably attend to the meeting. I really think that before arriving to the hackathon we should start talking about the standarization of the spectra in Json. We should arrive there to code and discuss small details.

**Comment by caetera** [comment]
@ypriverol of course, I will include you, however, I believe, the development of JSON spectra format is a separate project, that is only partially overlapping with the topic of the project I am suggesting. For example, the representation of a bunch of XICs has not much in common with the representation of LC-MS run (a bunch of mass spectra). I agree with you, that having a common (standardized) understanding of what and how should JSON spectrum format look like is important, however, my fear is it will take quite some time before we arrive at anything solid. So, yes, we should start talking about it, however, I don't want to risk ending up with nothing before the hackathon. As you can see from the project draft, I tried to limit the JSON format discussion to the necessary minimum, with clear intention to keep extendable (i.e. one can take the representation of a chromatogram or a spectrum and use them as a part of something larger).
In my opinion, it is okay to have a hackathon project aiming to draft the JSON spectra format. Although it is not that much fun (coding), but it is totally in the scope of the developer meeting. That is to say, I am happy to participate in the development/discussion of JSON spectra format and agree that that has to be initiated ASAP, and, if this discussion will end up in some kind of draft specifications until January, we will consider them during hackathon, but if not, I believe, it is important to start with something (although not perfect), of course, having a biger picture in mind.

**Comment by nielshulstaert** [comment]
Hi @caetera yes please include me, thanks!

**Comment by nielshulstaert** [comment]
Features added at the eubic 2020 developers meeting in nyborg and released in version 1.2.0. Thanks Vladimir and Yasset for initiating this!
