### ISSUE TITLE
Statically-linked binaries

### ISSUE THREAD

**Issue by prvst** [compomics/ThermoRawFileParser#61]
Hi, 

I really appreciate this project! I have plans to add it to [Philosopher](http://philosopher.nesvilab.org), but in order to do so we need to have statically-linked binaries. I'm not sure Jetbrains, but Mono has a tool that is specially designed to do that.

I was able to compile the project on Monodevelop and run mkbundle on the executable, the resulting binary works but only on a machine with Mono installed. If Mono is not installed, I get 'missing DLL errors'. I would really appreciate if someone could take a look at their instructions and see if its possible to make it full static.

https://www.mono-project.com/docs/tools+libraries/tools/mkbundle/

Thanks

**Comment by nielshulstaert** [comment]
Hi,

Thanks for the suggestion and my apologies for the late reply. What platform do you want to build it for?

**Comment by tomas-pluskal** [comment]
I would like to do the same for MZmine (https://mzmine.github.io). Ideally for Mac, Windows, and Linux. But I guess if we figure out how to do it for one platform, the rest can be inferred.

**Comment by prvst** [comment]
Thanks for replying.
Could you assemble binaries for Windows and Linux ?

**Comment by tomas-pluskal** [comment]
If we figure out the protocol how to do it, then sure I can do it.

**Comment by nielshulstaert** [comment]
Hi,

I managed to create a working one for ubuntu 18. Initially I got the same error as you, here's what I did (on a ubuntu 18 virtual machine):

First get the appropriate platform

``
mkbundle --list-targets
mkbundle --fetch-target mono-6.6.0-ubuntu-18.04-x64
``

Then edit the mono config file, in this case in ``user_home/.mono/targets/mono-6.6.0-ubuntu-18.04-x64/etc/mono/`` and get rid of all the ``$mono_libdir`` entries (see https://github.com/mono/mono/issues/16991), for example

``
<dllmap dll="System.Native" target="$mono_libdir/libmono-native.so" os="!windows" />
``

becomes

``
<dllmap dll="System.Native" target="libmono-native.so" os="!windows" />
``

And run the mkbundle command with the ``libmono-native.so`` as extra library

``
mkbundle -o RawFileParser --cross mono-6.6.0-ubuntu-18.04-x64 ThermoRawFileParser.exe --library /usr/lib/libmono-native.so
``

I've tested it on a Ubuntu 18 VM without mono and it seems to work, you need to keep the created ``RawFileParser`` file in the ``ThermoRawFileParser`` directory, otherwise it can't find the necessary dll's.

I didn't manage to create the Ubuntu 18 bundle on my arch linux machine (Error loading shared library version issue) so I think it's best to create the bundle on the platform you want to use it for.

For windows, the ThermoRawFileParser should work without mono.

**Comment by prvst** [comment]
thanks, I'll try that
