### ISSUE TITLE
Missing precursor intensity?

### ISSUE THREAD

**Issue by edeutsch** [compomics/ThermoRawFileParser#78]
Hi, we just noticed after starting to use ThermoRarFileParser a lot that it is missing the precursor intensity that msconvert writes out. e.g.:

msconvert:
`              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="541.310729980469" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                  <cvParam cvRef="MS" accession="MS:1000041" name="charge state" value="3"/>
                  <cvParam cvRef="MS" accession="MS:1000042" name="peak intensity" value="8923.3095703125" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/>
                </selectedIon>
              </selectedIonList>
`

while ThermoRawFileParser produces:
`              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" value="541.310729980469" name="selected ion m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
                  <cvParam cvRef="MS" accession="MS:1000041" value="3" name="charge state" />
                </selectedIon>
              </selectedIonList>
`

We found that Ids going into PeptideAtlas no longer have these precursor intensity values when we use ThermoRawFileParser.

Can we get these values filled in during ThermoRawFileParser conversion?

thanks!
Eric

**Comment by caetera** [comment]
Hi Eric,
since I am modifying mzML part for the other issue I can look if this information can be pulled out.

**Comment by caetera** [comment]
Hi @edeutsch ,

I have added the selected ion intensity. It is in the **uvdata** branch. The method to determine it is pretty simplistic, please, check if it works for you.

**Comment by edeutsch** [comment]
super, thanks! Do you plan on putting out a release soon with that in here?

**Comment by caetera** [comment]
There should be a release in near future, it will depend also on #60

**Comment by caetera** [comment]
You can give a pre-release version a try: https://filesender.deic.dk/?s=download&token=5b357204-cf9e-8bbb-4a1d-f601daafe98f

**Comment by edeutsch** [comment]
Thank you for implementing this! I have tested and it seems to work well. Most of the values are identical to those generated by msconvert. But many are also different. I have not investigated details of how some are different, but the difference is often substantial. It is unclear if msconvert values are more correct than ThermoRawFileParser values or not.

**Comment by caetera** [comment]
Hi @edeutsch, thank you for testing. Have you looked if the mass of the precursor is different as well, when the intensity is different? As to precursor mass, I guess we use the code similar to msconvert, (@nielshulstaert should know better) but maybe sometimes it gives slightly different result. There might be also some discrepancy if precursor is selected from a low resolution (IT) scan

**Comment by caetera** [comment]
I did a bit more investigation (just a random DDA file with MS1 in orbitrap) - MSConvert and ThermoRawFileParser report the same precursor mass and charge for all spectra and the same intensity for ~96% of them. I did manual validation of few (~10) spectra that had difference in reported intensity. I can see, that MSConvert reports intensity of some other peak nearby, or another peak within the isotopic cluster, but still uses the same precursor mass. ThermoRawFileParser always select the intensity of the same peak as reported by precursor mass. The peak with very close match to reported as selected m/z exists and it is not clear for me why MSConvert does not report it. It would be more logical to me to report different mass of precursor as well, if it uses different peak as precursor.
I also checked a DIA run, ThermoRawFileParser reports zero as precursor intensity, since the selected mass is not corresponding to any real peak. MSConvert still reports some value, but I have to say, that precursor intensity in case of DIA run is something not obvious, since there is no _real_ precursor ion.
If I will find any raw file with low resolution precursor scans, I will check it. Cannot grab any so far.

**Comment by edeutsch** [comment]
It looks like msconvert is putting in a different Monoisotopic M/Z userparam for these cases where it is different:

When the precursor intensity is the same:
                <cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="419.316741943359" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              <userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" value="419.31674194335937" type="xsd:float"/>

When the precursor intensity is different:
                <cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="521.138427734375" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
              <userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" value="519.140625" type="xsd:float"/>

**Comment by caetera** [comment]
closed with #125
