### ISSUE TITLE
instrument type etc. not in instrumentConfigurationList

### ISSUE THREAD

**Issue by mwalzer** [compomics/ThermoRawFileParser#79]
The instrument type cvParams are in a `referenceableParamGroup` on top-level instead of within a  instrumentConfigurationList/instrumentConfiguration. 
From the [specification](http://www.peptideatlas.org/tmp/mzML1.1.0.html#instrumentConfiguration) for the instrumentConfiguration tag: 
> Notes and Constraints:  Note that an instrument model MUST be provided.
Easy fix would be to move the referenceableParamGroup into a instrumentConfiguration tag.

**Comment by mwalzer** [comment]
Tested with v1.1.8 to 1.1.11
Nothing newer - quay.io is down right now

**Comment by mwalzer** [comment]
can confirm with v1.2.3

**Comment by caetera** [comment]
Hi @mwalzer, 
thank you for reporting this.
As I can read from the specification `referenceParamGroup` is `A collection of CVParam and UserParam elements that can be referenced from elsewhere in this mzML document`, so referencing this group as part of `instrumentConfiguration` should be a valid way to include instrument model (as required).
This way it is included in the example code provided in the specification

```xml
<referenceableParamGroupList count="3">
  <referenceableParamGroup id="CommonInstrumentParams">
    <cvParam cvRef="MS" accession="MS:1000448" name="LTQ FT" value=""/>
    <cvParam cvRef="MS" accession="MS:1000529" name="instrument serial number" value="SN06061F"/>
  </referenceableParamGroup>
  <referenceableParamGroup id="InstrumentCustomization">
    <cvParam cvRef="MS" accession="MS:1000032" name="customization" value="none"/>
  ...
</referenceableParamGroupList>
...
<instrumentConfiguration id="IC1">
  <referenceableParamGroupRef ref="CommonInstrumentParams"/>
  <componentList count="3">
    <source order="1">
      <cvParam cvRef="MS" accession="MS:1000073" name="electrospray ionization" value=""/>
      <cvParam cvRef="MS" accession="MS:1000057" name="electrospray inlet" value=""/>
      <cvParam cvRef="MS" accession="MS:1000486" name="source potential" value="4.20" unitCvRef="UO" unitAccession="UO:0000218" unitName="volt"/>
  ...
</instrumentConfiguration>
```

I have checked that **msconvert** (3.0.19329) implements it the same way. I agree that the use of `paramGroup` is _overkill_ here, since this information is used only once, but IMO it would be better to keep the compatibility with **msconvert** output, if it does not break any rules.

**Comment by mwalzer** [comment]
>better to keep the compatibility with msconvert

True.
