### ISSUE TITLE
Error with Fragpipe

### ISSUE THREAD

**Issue by 5utr** [compomics/ThermoRawFileParser#94]
I'm trying to use this converter with Fragpipe but I get an error that doesn't occur if I convert the RAW files to mzML  with msconverter and peakpicking filter.

This is the error msg:
`Cannot decode packed binary. expected element type <indexedmzML> but have <mzML>`

Any idea of what might cause it ?

**Comment by caetera** [comment]
Hi @5utr ,

Thank you for using ThermoRawFileParser. For us to be able to track the error better could you write which version are you using (standalone or docker)? Will it be possible for you to share the raw file?

**Comment by 5utr** [comment]
I'm using the standalone version

I uploaded the raw file, the conversion from msconvert and the conversion from thermorawfileparser here:

https://nextcloud.bcgsc.ca/index.php/s/JcJYtgyzEbKPncj


Thank you,

**Comment by caetera** [comment]
Hi again,

the error you get originates from FragPipe - `freequant` requires indexed mzML file, thus, it is necessary to use -f=2 in TRFP. MSConvert generates indexed mzML by default.

After converting your file with `-f=2` using version 1.3.2 of TRFP (I do not have now the version 1.1.11 that you used) it was successfully processed by FragPipe v14.0

**Comment by edeutsch** [comment]
I meant to mention months ago, but never did. But am now reminded: I think it would be advantageous to make `-f=2` the default. We always use `-f=2` and I suspect most users will want `-f=2` but they may not realize it. I think most mzML-using software works better with the index or only works with the index or works just as well with or without. And I suspect few if any software programs *don't* work with `f=2`, and thus mzML files with the index will be the most compatible and it seems like a friendly sensible default. I think it is the default for ProteoWizard.

Not having `-f=2` be the default is certainly not a bug, but probably is a potential (unecessary?) pitfall and a "support call generator"

Maybe making clearer that `-f=1` is NOT-INDEXED mzML rather than just "mzML" would help too. Since many users may stop reading at `-f=1` for 'mzML' and assume that's what they want.

**Comment by caetera** [comment]
Hi Eric,
thank you for your comment. You definitely have a valid point. I think it is good (and won't harm for sure) to make a distinction of "_plain_" and _indexed_ mzML more visible. I don't know what is the most common use pattern for the TRFP, I mean how often people use the default format (omit `-f` key), but changing default to `-f=2` is totally possible. I would like, though, to hear if someone has any objections to it, before making the change.

**Comment by 5utr** [comment]
Thank you for the quick reply, the -f 2 option works.

**Comment by nielshulstaert** [comment]
Hi Eric, Vladimir,

Sounds good to me, I'll add it to the next release and make it clear in the documentation.

**Comment by caetera** [comment]
Indexed mzML is the default output for version 1.3.3, thus, I think the issue can be closed. Please, reopen it, if necessary.
