### ISSUE TITLE
Use MsConvert for format conversion and get different results

### ISSUE THREAD

**Issue by imDpeng** [compomics/ThermoRawFileParser#96]
I used MsConvert and ThermoRawFileParser to convert the same rawfile respectively, and I did get different results. Why does this phenomenon occur? Does it affect the subsequent data analysis results?

system version: Linux dpeng-TianYi510Pro-18IKL 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
docker version: Docker version 20.10.1, build 831ebea

MsConvert version：chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:latest from docker hub
ThermoRawFileParser version：biocorecrg/thermorawparser:0.2 from docker hub

msconvert cmd:docker run -i --rm -e WINEDEBUG=-all -v /localpath:/data chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:latest wine msconvert.exe /data/sample.raw  --mzML -z -o  /data/mzgf/
ThermoRawFileParser cmd:docker run -v /localpath:/data_input -i -t --user biodocker biocorecrg/thermorawparser:0.2 mono /home/biodocker/bin/bin/x64/Debug/ThermoRawFileParser.exe -i=/data_input/raw_file.raw -o=/data_input/output/ -f=1 

raw file size:
-rw-r--r-- 1 dpeng dpeng 309951407 3月   4  2020 300M.raw
msconvert size:
-rw-r--r-- 1 dpeng  dpeng  707267053 12月 24 14:45 msconvert.mzML
ThermoRawFileParser size:
-rw-r--r-- 1 dpeng  dpeng  653330809 12月 24 14:15 ThermoRawFileParser.mzML

some detail:
1. The number of spectra of the data run by both is 115537
2. Find the same spectrum through metadata, the binary data is different.See the figure below for details, the left side is the result from ThermoRawFileParser, and the right side is the result of MsConvert.
![image](https://user-images.githubusercontent.com/48267340/103070572-bb37bf00-45fc-11eb-9d09-1f14610f4685.png)

**Comment by caetera** [comment]
Hi @imDpeng ,

Thank you for using ThermoRawFileParser. The first thing that I would like to check is the significance of the difference, i.e. it can be that we are talking about (so to say) rounding errors, i.e. the same number is represented slightly different (for example 123.12345678  and 123.12345677, of course I mean binary and not string representation) depending the platform or libraries used in msconvert docker and thermorawfileparser docker. I have seen this kind of differences earlier. It is next to impossible to deduce it from the screenshot you have provided. Will it be possible for you to calculate elementwise difference of binary arrays in question? Otherwise, can you share the mzML files with us (I can provide you with the link you can upload your mzML files if necessary). If the maximum elementwise difference will be small, i.e. < 1e-5 (that is, to the best of my knowledge, is the precision of the internal mass representation in RAW files), that should not result in any problems in the later steps of data processing.
Moreover, as I can see the docker you used comes with version 1.2.1 of ThermoRawFileParser, in version 1.2.3 we changed the way centroiding of IonTrap scans work (it should be more similar to msconvert), if the scan in question is the iontrap one (I cannot see it from the screenshot), that could be an explanation as well. In that case I might want to try using more recent docker image.
The "official" docker images for ThermoRawFileParser can be obtained from BioContainers https://quay.io/repository/biocontainers/thermorawfileparser?tag=latest&tab=tags (the latest version there is 1.2.3), the "inofficial" one is https://hub.docker.com/repository/docker/caetera/thermorawfileparser/general (the latest is version 1.3.2).
There is a separate issue #92 about gzip problem in biocontainers image that you should take into account.

**Comment by caetera** [comment]
Hi @imDpeng,

could you, please, tell us if the suggested solution work for you?

**Comment by imDpeng** [comment]
Of course it can, but I was working on another project recently, so I didn't conduct in-depth testing. Next, I will find time as soon as possible, test according to your suggestions, and then reply to you.

**Comment by caetera** [comment]
Sure. I only wanted to check if it works for you.
If you want, you can upload RAW and/or mzML files in question into this shared folder https://syddanskuni-my.sharepoint.com/:f:/g/personal/vgor_bmb_sdu_dk/EnSWhNBfa9JHj2t_JeTyklwBIwOcRXbB_-4l3WV3Y1iRzw?e=oxwEfd and I can look through it in my free time.

**Comment by imDpeng** [comment]
Because of network problems, file uploads always fail. The size of my MS file is only 300MB, so it is not convenient for you to send me your email. I will send the mass spec file to you by email.

**Comment by caetera** [comment]
I am afraid 300 Mb won't be accepted by my mail server, but I have another option for uploading - maybe it will work better.
https://filesender.deic.dk/?s=upload&vid=4554a75b-0ef5-5f2d-b93d-bbca15d0e59d

**Comment by imDpeng** [comment]
Uploaded, the address is https://filesender.deic.dk/?s=download&token=04580201-4d84-877c-2119-8ce446be4207

**Comment by caetera** [comment]
I have performed analysis of the file using the same docker images as you (the test system was Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-106-generic x86_64 and Docker 19.03.4, build 9013bf583a). I can share some results.
The file you uploaded does not contain scan 115537 (the one you mentioned in your opening post), so I cannot check this particular scan.

There is an obvious difference with MS1 scans. The default for msconvert is to provide profile representation, unless ` peakPicking` filter is used, TRFP uses peak picking by default (`-p` switches it off). I should have seen this already from the commands you have provided earlier, sorry for that.

The pairwise differences for m/z and intensity for all MS2 scans are all zero.

**Comment by caetera** [comment]
I will close the issue (since there was no any updates for almost a year), please, feel free to reopen, if necessary.
