### ISSUE TITLE
Accessing data from different "detectors" like pump pressure and temperatures

### ISSUE THREAD

**Issue by julianu** [compomics/ThermoRawFileParser#97]
Hi,

Is it possible to add an option (or is it there already and I missed it?) to export the values of "detectors" (name of them in Thermo's Freestyle) which monitor the loading and NC pump, the column oven temperature, or e.g. the UV? Maybe even other measurements, but these are the ones I would be interested in.
The data should be there in the RAW files, but I don't know whether Thermo's RawFileReader gives access to it.

Best and thanks,
Julian

**Comment by caetera** [comment]
Hi Julian,

since 1.3.0 there is an option to extract __all detector__ data with `-a|--allDetectors`. It will include, UV data, PDA data, and also try to find pressure data. UV and pressure data are stored as UV and pressure chromatograms in mzML. Note, that pressure data is stored sometimes as a **A/D detector** trace, the software search for traces that have word **pressure** in their name and extracts these as pressure chromatograms. It works for Dionex HPLCs, but might not work for other LC systems.
Please, let me know, if it helps.

**Comment by julianu** [comment]
That looks exactly like what I was looking for, great.
So I was a bit behind with the versions and CLI arguments, thanks for pointing me there.
