### ISSUE TITLE
MSconvert differences and error with Fragpipe

### ISSUE THREAD

**Issue by 5utr** [compomics/ThermoRawFileParser#98]
I converted some raw files with the standalone version 1.3.2 and the parameter -f2. When I try to process the files with Fragpipe v14 I get errors in the Freequant part for some of the converted files but not for others. If the same files are converted with MSconvert I don't get the error.

I uploaded some of the files for comparison:
https://nextcloud.bcgsc.ca/index.php/s/TRPMntGdDzWgLde

Specifically the f04538_Prot_01_01_TRFP.mzML returns an error while f04726_Prot_02_01_TRFP.mzML does not. 

time="09:02:06" level=info msg="Indexing PSM information"
time="09:02:06" level=info msg="Reading spectra and tracing peaks"
time="09:02:06" level=info msg="Processing f04538_Prot_01_01"
panic: runtime error: index out of range [0] with length 0

The same file f04538_Prot_01_01 converted with MSconvert (with these parameters https://github.com/Nesvilab/MSFragger/blob/master/tutorial_convert.md) doesn't produce the error.

**Comment by caetera** [comment]
Hi @5utr 

will also be possible for you to provide the raw file?

**Comment by 5utr** [comment]
Hi @caetera I added the raw files to the same folder.

**Comment by caetera** [comment]
I think I could fix the error. The issue was with handling of empty (zero ms points) spectra. You can download the precompiled beta version using this link https://syddanskuni-my.sharepoint.com/:u:/g/personal/vgor_bmb_sdu_dk/EQUDjsllf0JLjKesfCMamD8BMWQ5XD2pZG_GSX7rvV87Iw?e=05PelN or build it from the source in `Issue98` branch in git.
Please, let me know if it works as expected.

**Comment by 5utr** [comment]
The beta version works. Thank you.

**Comment by caetera** [comment]
Great. The release will be out in some future.
